@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Autocomplete Process LOGIC_COLOR_T1
actor "user" as user
participant ":CommandBox" as commandbox LOGIC_COLOR
participant "ghost:Ghost" as ghost LOGIC_COLOR
participant "AutocompleteParser" as autocompleteParser <<class>> LOGIC_COLOR
participant "AutocompleteSupplier" as autocompleteSupplier <<class>> LOGIC_COLOR
end box

user -> commandbox : type
activate commandbox

commandbox -> ghost : acRefreshGhostPreview(commandField)
activate ghost

    ghost -> autocompleteParser : command(text, caret)
    activate autocompleteParser

    alt command = add or sort
        autocompleteParser -> autocompleteSupplier : giveAddSortParams(text)
        activate autocompleteSupplier
        return suggestion
    else command = edit
        autocompleteParser -> autocompleteSupplier : giveEditParams(text)
        activate autocompleteSupplier
        return suggestion
    else complete command
        autocompleteParser -> autocompleteSupplier : bestMatch(text)
        activate autocompleteSupplier
        return suggestion
    end

    autocompleteParser -> autocompleteSupplier : makeTail(suggestion, prefix)
    activate autocompleteSupplier
    return tail
return command

alt "show" command: command[0] = "show"
  ghost -> ghost : updateState(command[1], command[2])
  ghost -> ghost : updateLabelAndShow(command[3], acGhostItem, commandField)
else "hide" command: command[0] = "hide"
  ghost -> ghost : acGhostHide()
end

user -> commandbox : tab
opt ghost != null
commandbox -> ghost : acCommitSuggestion(commandField)
activate ghost
return modified commandField
end
return

@enduml




