@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
class "CommandBox" as CommandBox
class "Ghost" as Ghost

}

package Logic {
class "AutoCompleteSupplier" as AutoCompleteSupplier
class "AutoCompleteParser" as AutoCompleteParser
}

Ghost .. AutoCompleteParser : <<◀commands>>
Ghost <-- CommandBox : <<◀reads>>
AutoCompleteParser .down. AutoCompleteSupplier : <<▲suggests>>

@enduml
