@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":CommandHistory" as commandHistory MODEL_COLOR_T1

user -> ui : handleUpDownKeyPress(event, commandBox)
activate ui

alt UP key pressed
    ui -> logic : getPreviousCommand()
    activate logic

    logic -> model : getPreviousCommand()
    activate model

    model -> commandHistory : getPreviousCommand()
    activate commandHistory

    commandHistory --> model : previousCommand
    deactivate commandHistory

    model --> logic : previousCommand
    deactivate model

    logic --> ui : command
    deactivate logic

else DOWN key pressed
    ui -> logic : getNextCommand()
    activate logic

    logic -> model : getNextCommand()
    activate model

    model -> commandHistory : getNextCommand()
    activate commandHistory

    commandHistory --> model : nextCommand
    deactivate commandHistory

    model --> logic : nextCommand
    deactivate model

    logic --> ui : command
    deactivate logic
end


ui -> logic : getCommandHistory()
activate logic

logic -> model : getCommandHistory()
activate model

model -> commandHistory : toString()
activate commandHistory

commandHistory --> model : formattedCommandHistory
deactivate commandHistory

model --> logic : formattedCommandHistory
deactivate model

logic --> ui : formattedCommandHistory
deactivate logic

ui -> ui : event.consume()

ui --> user
deactivate ui

@enduml
