@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":CommandHistory" as commandHistory LOGIC_COLOR_T1

user -> ui : handleUpDownKeyPress(event, commandBox)
activate ui

alt UP key pressed
    ui -> logic : getNextCommand()
    activate logic

    logic -> commandHistory : getNextCommand()
    activate commandHistory

    commandHistory --> logic : nextCommand
    deactivate commandHistory

    logic --> ui : command
    deactivate logic


else DOWN key pressed
    ui -> logic : getPreviousCommand()
    activate logic

    logic -> commandHistory : getPreviousCommand()
    activate commandHistory

    commandHistory --> logic : previousCommand
    deactivate commandHistory

    logic --> ui : command
    deactivate logic
end


ui -> logic : getCommandHistory()
activate logic

logic -> commandHistory : toString()
activate commandHistory

commandHistory --> logic : formattedCommandHistory
deactivate commandHistory

logic --> ui : formattedCommandHistory
deactivate logic

ui -> ui : event.consume()

ui --> user
deactivate ui

@enduml
